### ISSUE TITLE
How to set instance endpoint?

### ISSUE THREAD

**Issue by lissy93** [BiciP/plausible-mobile#1]
Heya @BiciP, this looks like a sweet app, but after downloading and adding API keys, I've not been able to figure out how to actually point it to my Plausible instance. Is there somewhere I should enter the endpoint and port?

**Comment by BiciP** [comment]
At the moment, setting a custom endpoint is not supported, but it is high on the to-do list.

**Comment by BiciP** [comment]
Feature is available from app version 1.0.3 onwards. Closing this issue
